Created boxfile-00_dokku-standard with MM changes

diff --git a/plugins/boxfile-00_dokku-standard/commands b/plugins/boxfile-00_dokku-standard/commands
--- a/plugins/boxfile-00_dokku-standard/commands
+++ b/plugins/boxfile-00_dokku-standard/commands
@@ -11,10 +11,23 @@ case "$1" in
 
     case "$IMAGE_SOURCE_TYPE" in
       buildstep)
+        # CHECK FOR composer.json
+        if [[ ! -f "$TMP_WORK_DIR/composer.json" ]] ; then
+          echo -e "\n       \033[0;31mcomposer.json or Dockerfile is required\033[0m\n\n"
+          exit 1
+        fi
+
+        # Begin building the Boxfile
+        dokku_log_info2 "Parsing composer.json"
+
+        # Begin building out application
+        echo -e "\n       \033[0;32mBuilding Application\033[0m\n\n"
+
         id=$(tar -c . | docker run -i -a stdin $DOKKU_IMAGE /bin/bash -c "mkdir -p /app && tar -xC /app")
         test "$(docker wait $id)" -eq 0
         docker commit $id $IMAGE > /dev/null
         [[ -d $CACHE_DIR ]] || mkdir $CACHE_DIR
+
         # *DEPRECATED* in v0.4.0: `pluginhook pre-build` will be removed in future releases
         pluginhook pre-build "$APP"
         pluginhook pre-build-buildstep "$APP"
@@ -23,6 +36,7 @@ case "$1" in
         # https://github.com/progrium/dokku/issues/896 & https://github.com/progrium/dokku/issues/906
         DOCKER_ARGS=$(: | pluginhook docker-args $APP build)
         DOCKER_ARGS+=$(: | pluginhook docker-args-build $APP)
+        DOCKER_ARGS+=" -e BUILDPACK_URL=https://github.com/modernmedia/php-buildpack"
         id=$(docker run -d -v $CACHE_DIR:/cache -e CACHE_PATH=/cache $DOCKER_ARGS $IMAGE /build/builder)
         docker attach $id
         test "$(docker wait $id)" -eq 0
@@ -34,10 +48,10 @@ case "$1" in
         ;;
 
       dockerfile)
+        pluginhook pre-build-dockerfile "$APP"
         # sticking with same pattern of building app image before pre-build for now.
         docker build -t "$IMAGE" .
         # buildstep pluginhooks don't necessarily make sense for dockerfiles. call the new breed!!!
-        pluginhook pre-build-dockerfile "$APP"
         pluginhook post-build-dockerfile "$APP"
         ;;
 
